### ISSUE TITLE
[SWITCHYARD-2053]NPE when SoapV12 fault has no faultactor

### ISSUE THREAD

**Issue by luozengbin** [jboss-switchyard/components#670]
In SoapV1.2 when service provider return a soap fault without faultactor element [SOAPUtil](https://github.com/jboss-switchyard/components/blob/master/soap/src/main/java/org/switchyard/component/soap/util/SOAPUtil.java) will NPE when converting that to a SOAPFault. There was a similar bug in Apache CXF before. [Apache CXF issue link](https://issues.apache.org/jira/browse/CXF-4265) 

```
Caused by: java.lang.NullPointerException
    at com.sun.xml.messaging.saaj.soap.impl.ElementImpl.addTextNode(ElementImpl.java:455)
    at com.sun.xml.messaging.saaj.soap.ver1_2.Fault1_2Impl.setFaultRole(Fault1_2Impl.java:338)
    at com.sun.xml.messaging.saaj.soap.ver1_2.Fault1_2Impl.setFaultActor(Fault1_2Impl.java:574)
    at org.switchyard.component.soap.util.SOAPUtil.generateFault(SOAPUtil.java:470) [switchyard-component-soap-1.1.1-p5-redhat-1.jar:1.1.1-p5-redhat-1]
    at org.switchyard.component.soap.util.SOAPUtil.generateSOAP12Fault(SOAPUtil.java:453) [switchyard-component-soap-1.1.1-p5-redhat-1.jar:1.1.1-p5-redhat-1]
    at org.switchyard.component.soap.util.SOAPUtil.generateFault(SOAPUtil.java:426) [switchyard-component-soap-1.1.1-p5-redhat-1.jar:1.1.1-p5-redhat-1]
    at org.switchyard.component.soap.OutboundHandler.invokeService(OutboundHandler.java:332) [switchyard-component-soap-1.1.1-p5-redhat-1.jar:1.1.1-p5-redhat-1]
    at org.switchyard.component.soap.OutboundHandler.handleMessage(OutboundHandler.java:273) [switchyard-component-soap-1.1.1-p5-redhat-1.jar:1.1.1-p5-redhat-1]
    at org.switchyard.bus.camel.processors.ProviderProcessor.process(ProviderProcessor.java:29) [switchyard-bus-camel-1.1.1-p5-redhat-1.jar:1.1.1-p5-redhat-1]
    at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) [camel-core-2.10.0.redhat-60024.jar:2.10.0.redhat-60024]
```

**Comment by tadayosi** [comment]
@luisdeltoro,

Now you have to submit a PR against https://github.com/jboss-switchyard/switchyard instead of this repo. This repo has been deprecated after SY 2.0 release.
